spring:
  application:
    name: "fundicion-lara"
    version: "1.0.1"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "${PORTFOLIO_REAL_SERVICE_DATASOURCE_URL:jdbc:mysql://localhost:3306/fundicion_lara_db}"
    username: "${DATASOURCE_USERNAME:root}"
    password: "${DATASOURCE_PASSWORD:root}"
    hikari:
      maximum-pool-size: "${MAXIMUM_POOL_SIZE:10}"

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework: WARN
      hibernate:
        SQL: ERROR